server:
  port: 8082

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/helpdesk_users}
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
